config:
  app_secret: "donler_gym_app_secret"
  # token过期时间为30天
  token_expired_time: "2592000000"



# OSS的配置

#oss:
#  endpoint: "http://donler-gym.oss-cn-qingdao.aliyuncs.com"
#  access_key_id: "L33bxhzrpnRBLizQ"
#  access_key_secret: "6P1vpfW9nGU8FtcGBSYAubfuBLjlf6"
#  bucket_name: "donler-gym"
#  key: "mykey"


# in-memory
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#    show-sql: true
#
#  datasource:
#    url: jdbc:hsqldb:mem:gym
#
# in-mysql

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gym_dev?useSSL=false
    test-on-borrow: true
    validation-query: select 1
    validation-query-timeout: 5000
    username: root
    password: root

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

---
spring.profiles: production
spring:
  jpa:
    hibernate:
      ddl-auto: update